spring:
  application:
    name: auth-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${spring.application.name}


server:
  port: 8090

service:
  kafka:
    topics:
      registration: auth.registration